### ISSUE TITLE
Contact us form does not work, it won't submit

### ISSUE THREAD

**Issue by shuki25** [gitlocalize/feedback#103] opened 2021-04-11 15:39 UTC
### Summary

Tried to use your contact us form on your gitlocalize.com website. After submitting the form, it failed, it said "* User must exist". So we are unable to send any messages to you.

### Steps to reproduce

Go to contact us form, fill out the form and submit. (Not logged into gitlocalize.com)

### Repository URL

(If possible, please paste repository URLs which have errors.)

### What is the current *bug* behavior?

Doesn't get submitted. Error showing up "* User must exist"

### What is the expected *correct* behavior?

The form should be submitted without any problem.

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/31372342/114310972-d8fd3700-9aba-11eb-9e81-30ebb9b7f0bc.png)

### Possible fixes

(If you have any idea to solve the problem, please help us.)

**Comment by ezra-en** [comment] 2021-04-19 14:36
The Contact Us form seems to assume that only current users of GitLocalize should be able to use the form itself. It seems likely that the former account data may not have been transferred over, which may mean that this requires manual intervention on the part of GitLocalize's operations team. This is unfortunately not a bug, but intended behaviour. Not very useful behaviour in this case though.

**Comment by svasilenkov** [comment] 2021-06-24 13:45
Thank you for reporting this, I've forwarded this to the development team. By the way, we have fixed the issue with logging into GitLocalize, please try again.

**Comment by ilyaspiridonov** [comment] 2022-02-23 21:01
fixed

**Closed as completed by ilyaspiridonov** 2022-02-23 21:01 UTC
