### ISSUE TITLE
Failed to create a pull request

### ISSUE THREAD

**Issue by veenaiyuri** [gitlocalize/feedback#108] opened 2021-11-17 11:36 UTC
### Summary

Failed to create a pull request
https://gitlocalize.com/repo/6741/ja/review/36839

### Steps to reproduce

1. Create a Review Request
2. Then Send Pull Request

### Repository URL

https://gitlocalize.com/repo/6741/ja/review/36774

### What is the current *bug* behavior?

Status shows "Failed to create a pull request." as shown in the image below.
![image](https://user-images.githubusercontent.com/24409087/142193087-135af892-c114-4efc-99d5-3c8863ac20af.png)

### What is the expected *correct* behavior?

Successful creation of a pull request.

**Comment by svasilenkov** [comment] 2021-11-17 12:29
@veenaiyuri Thank you for the feedback! We have forwarded it to our development team and will let you know as soon as we find a solution.

**Comment by veenaiyuri** [comment] 2022-01-07 03:23
Hi @svasilenkov !  Happy New Year! I want to follow up on this issue because I am anxious to kick start our localization efforts for the new year. Please let me know the status of the investigation. Thanks!

**Comment by ilyaspiridonov** [comment] 2022-02-23 21:05
I'm closing this issue for now, as this is not a system-wide issue, and was rather caused by the specific structure of the .ipynb in the original project (Jupyter notebooks without cell IDs). 
We are now in the process of implementing support for this kind of Jupyter notebooks - the task is currently in production with our dev team.

**Closed as completed by ilyaspiridonov** 2022-02-23 21:05 UTC
