### ISSUE TITLE
*.md path rules cannot be synced from source

### ISSUE THREAD

**Issue by ivan-nginx** [gitlocalize/feedback#42] opened 2018-01-21 23:52 UTC
### Summary

Some additional path rules (in my example this is *.md files) cannot be synced from source (by push «Sync» button too).

### Steps to reproduce

1. Add in [settings](https://gitlocalize.com/repo/*/settings) additional path rule:
    ```
    File or Directory: File
    Source Path: docs/MATH.md
    Translation Path: docs/%lang%/MATH.md
    ```
2. Submit. Sync. Go to translate some, all ok, all fine.
3. Change original `docs/MATH.md` in source repo. Rechecked twice: branch - ok.
4. Go to translates panel and want to see changed `docs/MATH.md`, but it's old version.
5. Go to [settings](https://gitlocalize.com/repo/*/settings), try:
    5.1. Sync, awaiting some time, back in translates panel, check source lang — no succes.
    5.2. Trying to remove this path from Path Rules; Submit; Sync, check source lang — file removed, percent also increased/decreased. It's ok, fine.
    5.3. Trying to add this path in again (accordiance with main section 4 above); Submit; Sync, check source lang again — no success. Previous percent, previous translate strings.

### Repository URL

* Repo: https://github.com/theme-next/hexo-theme-next/issues/57
* Files in docs: https://github.com/theme-next/hexo-theme-next/tree/master/docs
* For now 2 branches (master and i18n) and both synced.

### What is the current *bug* behavior?

Original source *.md file doesn't update and resync correctly. Even if i push «Sync» button.

### What is the expected *correct* behavior?

When original source *.md file changed in source repo, after push «Sync» it must resync this source to original source lang file.

### Possible fixes

I understand what this files cached for better speed, and suggest to add something like button in each path rule:
![image](https://user-images.githubusercontent.com/16944225/35200364-0bf825fc-ff1e-11e7-9afe-4eca3005a250.png)

OR

At least fix main «Sync» button to instant update all possible sources for all Path Rules.
![image](https://user-images.githubusercontent.com/16944225/35200426-2c6de62c-ff1f-11e7-837c-b9ee390884b5.png)

**Comment by theJoshMuller** [comment] 2021-03-21 10:52
I've been noticing this issue, too. Was there ever any fix supplied for it? I'm working on a project that has an often changing Master file that translations will be regularly created from. It'd be nice if there was a way to ensure translators are working from the most recent copy of a file

**Comment by ilyaspiridonov** [comment] 2021-03-21 11:54
@joshdm42 Thanks for raising this again. We use Github webhooks to track changes in source files, so by design the Gitlocalize project should update each time the source file (or even the translation file, for that matter) is updated. 
However, we're sometimes seeing this logic does not work as intended. Here are some possible causes: 
- GitHub not properly sending webhooks.
- Webhooks are sent, but not processed correctly on our end.
- App installation failed (e.g. insufficient permissions etc.)
We would like to investigate what exactly is happening in your case: which repo/file are you experiencing this with? 
Thanks! 
@svasilenkov FYI

**Comment by theJoshMuller** [comment] 2021-03-21 16:03
Here is the [source file](https://github.com/joshdm42/alephwithbethvideos/blob/main/i18n/en.yaml) and the [target file](https://github.com/joshdm42/alephwithbethvideos/blob/main/i18n/es.yaml). At the moment, GitLocalize isn't showing the English updates on the [translation page](https://gitlocalize.com/repo/5939/es/i18n/en.yaml) (👈🏽 not sure if you can see that link as a GitLocalize.com admin, but I'll throw it out there just in case).

**Comment by svasilenkov** [comment] 2021-03-22 13:49
@joshdm42 I've checked the latest updates of the source file at GitHub and it seems that they are synced with GitLoclalize. Could you please check and point to a specific YAML keys that are not synced?

**Comment by theJoshMuller** [comment] 2021-03-24 09:18
Interesting. At the time of my post `Introduction-Videos.other`, and any other tag added after that hadn't appeared to be synced. 

Now it seems to be working 🤔. That's a good sign, but confusing 😅.

**Comment by ilyaspiridonov** [comment] 2021-03-25 17:32
@joshdm42 Thanks for the heads-up, it looks like there was a delay in sending or processing the webhook. I'm closing this but please feel free to reopen in case this gets reproduced, we'll conduct a more thorough investigation.

**Closed by ilyaspiridonov** 2021-03-25 17:32 UTC
